version: '2'
services:

  db-dev:
    image: postgres:10
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=books
    ports:
      - "5432:5432"

volumes:
  server-dev:
